language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - '6'

sudo: required # Required for the ENOSPC fix
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-canary-legacy-decorators

  include:
    # runs linting and tests with current locked deps

    - stage: 'Tests'
      name: 'Tests'
      script:
        - yarn lint:hbs
        - yarn lint:js
        - yarn lint:types
        - yarn test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: 'Additional Tests'
      env: EMBER_TRY_SCENARIO=ember-lts-2.12
    - env: EMBER_TRY_SCENARIO=ember-lts-2.12-legacy-decorators
    - env: EMBER_TRY_SCENARIO=ember-lts-2.16
    - env: EMBER_TRY_SCENARIO=ember-lts-2.16-legacy-decorators
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18-legacy-decorators
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4-legacy-decorators
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-release-legacy-decorators
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-beta-legacy-decorators
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-canary-legacy-decorators

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  # Fixes an issue where the max file watch count is exceeded, triggering ENOSPC
  # https://stackoverflow.com/questions/22475849/node-js-error-enospc#32600959
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

install:
  - yarn install --no-lockfile --non-interactive

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
